### ISSUE TITLE
Loop Support

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vds-player#93]
## Tasks

- [x] Complete #8.
- [x] Design, implement and test an interface to support looping videos.

## Notes

This will expand the player API:

**Properties**

- `loop: boolean`

**Events**

- `vds-loop`

Keep the logic in the player by simply resetting the current-time - avoid using provider specific implementations.

**Comment by tomByrer** [comment]
v1.1 suggestion: add ability to set loop points (eg 00:05:100 - 00:12:310) within the video.  Helpful when trying to memorize an instructional video.

**Comment by mihar-22** [comment]
Thanks for the suggestion @tomByrer, definitely a useful feature and happy to discuss it later, but for now it would require it's own issue/ticket.
