### ISSUE TITLE
Idea: use State Machines for logic & some state

### ISSUE THREAD

**Issue by tomByrer** [vidstack/vds-player#95]
I was looking to build my own video player using a [State Machine](https://statecharts.github.io/what-is-a-state-machine.html) to handle the business logic (& state) between the API & UI.  I was about to borrow code from you Vime project, but saw this is now Vime v6.0?  However you `.gitignore` all the source code, so I'm unsure if you'd like to work together?

Here is a simple [mute swtich](https://xstate.js.org/viz/?gist=dadd3c237aa1cca572fd5d8dadfad31a) demo of a State Machine.
( Click on the blue buttons on the left to change the state, which you can review in the STATE tab on the right. )

Honestly, too simple.  But when you [add a volume changer](https://xstate.js.org/viz/?gist=293787d6f2afe9d4a79cdba56591a78c), you can see how it can help more complex flows.  Just 2 states & 4 events save some more complex if/then or case statements.
( To set the volume, you need to 'send' a value along with an event.  So in the EVENTS tab on the right, paste the following into the bottom input, then click [SEND] )
```js
{
  "type": "VOL_CHANGE",
  "value": 0.9
}
```
![image](https://user-images.githubusercontent.com/1308419/107178206-4b597a00-6999-11eb-9a36-18ca5a82b22f.png)
Then in the STATE tab, you should see `context.volume` to be 0.9

**Comment by mihar-22** [comment]
>  I was about to borrow code from you Vime project, but saw this is now Vime v6.0?

Yes this is the successor to Vime 5.x and Plyr 3.x.

> However you `.gitignore` all the source code, so I'm unsure if you'd like to work together?

I'm not sure what you mean? I haven't ignored the `src` directory and also included it in the final package distribution. I'm completely open to outside contributions and work 😄 

>  I was looking to build my own video player using a State Machine to handle the business logic (& state) between the API & UI.

Using XState is an interesting idea but I can't see much value for adding it to the library as we already have a rich event system (which is required for features like analytics/telemetry). In the case of making the web components more consumer friendly I believe it's best to stick to a standard design pattern such as events. Two simple reasons why I wouldn't use Xstate is to avoid dependency overhead (one-less thing to learn for new contributors or anyone trying to understand the player internals), and the [package is way too big](https://bundlephobia.com/result?p=xstate@4.16.2) even after treeshaking to be used in a component library.

In addition, the player is designed as a state machine. The possible states and their transitions are defined by the events contract and the player. For example, we know `muted` can only be either muted or unmuted. Thus, we create events for the UI to transition between states such as `UserMuteRequest` and `UserUnmuteRequest`. Ultimately, only the player can decide what intent these events translate to and in this case it's simply setting the `muted` property to `true` or `false` on the provider which in turn reflects the true state (single source of truth) of the player.

**Comment by tomByrer** [comment]
> .gitignore

This part of [your file](https://github.com/vidstack/vds-player/blob/16fe1cb01fb33e9295f2d80f9a2864a47522d5c2/.gitignore#L2-L9):
```
@types/
/bundle/
/core/
/providers/
/skins/
/ui/
/utils/
```
Seems to make all of your files in /src to either disappear, or have a filesize of [0Kb](https://github.com/vidstack/vds-player/blob/main/src/ui/ui/index.ts) (zero).

> required for features like analytics/telemetry

That's a great reason by itself!

> package is way too big 

Good point, though I was thinking of using the [smaller 3.5kb brother, FSM](https://bundlephobia.com/result?p=@xstate/fsm@1.6.0); sorry I wasn't clear. (XState is a Statechart, FSM is State Machine; Statecharts are super-deluxe.)

Thanks for your insights!  I do like how you isolate concerns, rather than intermingling too much.

**Comment by mihar-22** [comment]
> Seems to make all of your files in /src to either disappear, or have a filesize of 0Kb (zero).

Oh haha no there's simply just no code there yet because we haven't started building the player... actually starting today/tomorrow 😄

**Comment by mihar-22** [comment]
Closing for now but thanks for sharing these ideas. Feel free to re-open if anything new comes up.
